CFLAGS=-Wall -O0 -ggdb3 -DDEBUG=1
LIBFILES=quickhash.c iterator.c

all: test1 test2 test3 test4 test5 test6 test7 test8 test9 test10 test11 test12

test1: test1.c $(LIBFILES)
	gcc $(CFLAGS) -o test1-64 test1.c $(LIBFILES)
	gcc -m32 $(CFLAGS) -o test1-32 test1.c $(LIBFILES)

test2: test2.c $(LIBFILES)
	gcc $(CFLAGS) -o test2-64 test2.c $(LIBFILES)
	gcc -m32 $(CFLAGS) -o test2-32 test2.c $(LIBFILES)

test3: test3.c $(LIBFILES)
	gcc $(CFLAGS) -o test3-64 test3.c $(LIBFILES)
	gcc -m32 $(CFLAGS) -o test3-32 test3.c $(LIBFILES)

test4: test4.c $(LIBFILES)
	gcc $(CFLAGS) -o test4-64 test4.c $(LIBFILES)
	gcc -m32 $(CFLAGS) -o test4-32 test4.c $(LIBFILES)

test5: test5.c $(LIBFILES)
	gcc $(CFLAGS) -o test5-64 test5.c $(LIBFILES)
	gcc -m32 $(CFLAGS) -o test5-32 test5.c $(LIBFILES)

test6: test6.c $(LIBFILES)
	gcc $(CFLAGS) -o test6-64 test6.c $(LIBFILES)
	gcc -m32 $(CFLAGS) -o test6-32 test6.c $(LIBFILES)

test7: test7.c $(LIBFILES)
	gcc $(CFLAGS) -o test7-64 test7.c $(LIBFILES)
	gcc -m32 $(CFLAGS) -o test7-32 test7.c $(LIBFILES)

test8: test8.c $(LIBFILES)
	gcc $(CFLAGS) -o test8-64 test8.c $(LIBFILES)
	gcc -m32 $(CFLAGS) -o test8-32 test8.c $(LIBFILES)

test9: test9.c $(LIBFILES)
	gcc $(CFLAGS) -o test9-64 test9.c $(LIBFILES)
	gcc -m32 $(CFLAGS) -o test9-32 test9.c $(LIBFILES)

test10: test10.c $(LIBFILES)
	gcc $(CFLAGS) -o test10-64 test10.c $(LIBFILES)
	gcc -m32 $(CFLAGS) -o test10-32 test10.c $(LIBFILES)

test11: test11.c $(LIBFILES)
	gcc $(CFLAGS) -o test11-64 test11.c $(LIBFILES)
	gcc -m32 $(CFLAGS) -o test11-32 test11.c $(LIBFILES)

test12: test12.c $(LIBFILES)
	gcc $(CFLAGS) -o test12-64 test12.c $(LIBFILES)
	gcc -m32 $(CFLAGS) -o test12-32 test12.c $(LIBFILES)
